on: [push, pull_request_review]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test requirements
        run: |
          pip install --upgrade pip pip-tools
          pip install ".[test]"

      - name: Check pythie-serving-requirements.txt
        run: |
          pip-compile --extra=serving --no-emit-index-url --quiet --output-file=pythie-serving-requirements.txt setup.py
          if ! [ -z "$(git status --porcelain)" ]; then
            echo "pythie-serving-requirements.txt are not sync'ed with setup.py, please run pip-compile.";
            false;
          fi

      - name: Lint (flake8)
        run: |
          flake8 .

      - name: Lint (black)
        run: |
          black . --check

      - name: Lint (isort)
        run: |
          isort . --check-only

      - name: Check typing (mypy)
        run: |
          mypy --install-types --non-interactive

      - name: Pyupgrade
        run: |
          pyupgrade --py311-plus

      - name: Run unit tests
        run: |
          pytest tests --junitxml=junit/test-results.xml
